# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                failure_path:   null
                default_target_path:  /
                always_use_default_target_path: true
                provider: fos_userbundle
                use_referer:    true
                csrf_token_generator: security.csrf.token_manager
                require_previous_session: false


            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                login_path:        /login
                use_forward:       false
                failure_path:      /login
                default_target_path: /user/profile/
                oauth_user_provider:
                    service: my.oauth_aware.user_provider.service

            remember_me:
                secret:   '%secret%'
                lifetime: 31536000 # 1 year in seconds
                path:     /

            logout:
                path:      /user/logout
                target:    /

            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }